Name:           perl-Term-Sk
Version:        0.18
Release:        3%{?dist}
Summary:        Perl extension for displaying a progress indicator on a terminal
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Term-Sk/
Source0:        http://www.cpan.org/authors/id/K/KE/KEICHNER/Term-Sk-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl-generators
BuildRequires:  perl(Exporter)
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(Fcntl)
BuildRequires:  perl(strict)
BuildRequires:  perl(Test::More)
BuildRequires:  perl(Time::HiRes)
BuildRequires:  perl(warnings)
Requires:       perl(Exporter)
Requires:       perl(Fcntl)
Requires:       perl(strict)
Requires:       perl(Time::HiRes)
Requires:       perl(warnings)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))
Provides:       perl(Term::Sk)

%description
Format strings

%prep
%setup -q -n Term-Sk-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%files
%defattr(-,root,root,-)
%doc Changes dist.ini LICENSE META.json README
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Thu Jun 16 2022 Stuart Campbell <scampbell@bnl.gov> - 0.18-3
- Added perl-generators to build dependencies

* Tue May  4 2021 Stuart Campbell (scampbell@bnl.gov) 0.18-2
- Added provides info

* Sun Apr 11 2021 Stuart Campbell (scampbell@bnl.gov) 0.18-1
- Specfile autogenerated by cpanspec 1.78.
