Name:           perl-Graphics-GnuplotIF
Version:        1.8
Release:        4%{?dist}
Summary:        Dynamic Perl interface to gnuplot
License:        CHECK(Distributable)
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Graphics-GnuplotIF/
Source0:        http://www.cpan.org/authors/id/M/ME/MEHNER/Graphics-GnuplotIF-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  gnuplot
BuildRequires:  perl-interpreter
BuildRequires:  perl-generators
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(Module::Build)
BuildRequires:  perl(Test::More)
BuildRequires:  perl(version)
Requires:       gnuplot
Requires:       perl(Test::More)
Requires:       perl(version)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))
Provides:       perl(Graphics::GnuplotIF)

%description
Graphics::GnuplotIF is a simple and easy to use dynamic Perl interface to
gnuplot. gnuplot is a freely available, command-driven graphical display
tool for Unix. It compiles and works quite well on a number of Unix
flavours as well as other operating systems, including Windows with
gnuplot.exe.

%prep
%setup -q -n Graphics-GnuplotIF-%{version}

%build
%{__perl} Build.PL --installdirs=vendor
./Build

%install
rm -rf $RPM_BUILD_ROOT

./Build install --destdir=$RPM_BUILD_ROOT --create_packlist=0
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
./Build test

%files
%defattr(-,root,root,-)
%doc Changes META.json README
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Mon Aug 19 2024 Stuart Campbell <scampbell@bnl.gov> - 1.8-4
- Added perl-interpreter to build dependencies

* Thu Jun 16 2022 Stuart Campbell <scampbell@bnl.gov> - 1.8-3
- Added perl-generators to build dependencies

* Thu May 06 2021 Stuart Campbell (scampbell@bnl.gov) 1.8-2
- Added provides info

* Sun Apr 11 2021 Stuart Campbell (scampbell@bnl.gov) 1.8-1
- Specfile autogenerated by cpanspec 1.78.
