Name:           perl-Pod-ProjectDocs
Version:        0.53
Release:        4%{?dist}
Summary:        Generates CPAN like project documents from pod
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Pod-ProjectDocs/
Source0:        http://www.cpan.org/authors/id/M/MG/MGRUNER/Pod-ProjectDocs-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  make
BuildRequires:  perl-generators
BuildRequires:  perl-interpreter
BuildRequires:  perl(Carp)
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(File::Basename)
BuildRequires:  perl(File::Copy)
BuildRequires:  perl(File::Find)
BuildRequires:  perl(File::Path)
BuildRequires:  perl(File::Spec)
BuildRequires:  perl(HTML::Entities)
BuildRequires:  perl(IO::File)
BuildRequires:  perl(JSON) >= 2.04
BuildRequires:  perl(lib)
BuildRequires:  perl(MIME::Base64)
BuildRequires:  perl(Moose)
BuildRequires:  perl(Pod::Simple::XHTML) >= 3.31
BuildRequires:  perl(Readonly)
BuildRequires:  perl(Template)
BuildRequires:  perl(Test::More)
BuildRequires:  perl(Test::Pod)
Requires:       perl(Carp)
Requires:       perl(File::Basename)
Requires:       perl(File::Copy)
Requires:       perl(File::Find)
Requires:       perl(File::Spec)
Requires:       perl(HTML::Entities)
Requires:       perl(IO::File)
Requires:       perl(JSON) >= 2.04
Requires:       perl(MIME::Base64)
Requires:       perl(Moose)
Requires:       perl(Pod::Simple::XHTML) >= 3.31
Requires:       perl(Readonly)
Requires:       perl(Template)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))
Provides:       perl(Pod::ProjectDocs)

%description
This module allows you to generates CPAN like pod pages from your modules
for your projects. It also creates an optional index page.

%prep
%setup -q -n Pod-ProjectDocs-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%files
%defattr(-,root,root,-)
%doc Changes.md cpanfile dist.ini LICENSE META.json perlcriticrc Readme.md
%{_bindir}/pod2projdocs
%{perl_vendorlib}/*
%{_mandir}/man1/*
%{_mandir}/man3/*

%changelog
* Fri Jun 17 2022 Stuart Campbell - 0.53-4
- Added perl-generators to build dependencies

* Fri Jun 17 2022 Stuart Campbell - 0.53-3
- Add make to build dependencies

* Mon May 03 2021 Stuart Campbell (scampbell@bnl.gov) 0.53-2
- Added Provides info

* Sun Apr 11 2021 Stuart Campbell (scampbell@bnl.gov) 0.53-1
- Specfile autogenerated by cpanspec 1.78.
